export const colors = {
  bgPrimary:   '#0f1117',
  bgCard:      '#1a1d27',
  bgHover:     '#252a37',
  bgInput:     '#1a1d27',
  border:      '#374151',
  borderHover: '#4B5563',
  borderFocus: '#3B82F6',
  textPrimary:   '#FFFFFF',
  textSecondary: '#D1D5DB',
  textMuted:     '#9CA3AF',
  textDisabled:  '#6B7280',
  blue:   '#3B82F6',
  green:  '#10B981',
  red:    '#EF4444',
  yellow: '#F59E0B',
  purple: '#8B5CF6',
  teal:   '#06B6D4',
};

export const tw = {
  page: 'min-h-screen bg-[#0f1117] text-white',
  card: 'bg-[#1a1d27] border border-gray-700 rounded-lg p-6',
  cardHover: 'bg-[#1a1d27] border border-gray-700 rounded-lg p-6 hover:border-gray-500 transition cursor-pointer',
  cardSm: 'bg-[#1a1d27] border border-gray-700 rounded-lg p-4',
  btnPrimary: 'px-6 py-3 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition',
  btnSecondary: 'px-6 py-3 bg-gray-700 hover:bg-gray-600 text-white font-semibold rounded-lg transition',
  btnDanger: 'px-6 py-3 bg-red-600 hover:bg-red-700 text-white font-semibold rounded-lg transition',
  btnSuccess: 'px-6 py-3 bg-green-600 hover:bg-green-700 text-white font-semibold rounded-lg transition',
  btnGhost: 'px-6 py-3 border border-gray-700 hover:bg-gray-700 text-gray-300 hover:text-white font-semibold rounded-lg transition',
  btnSm: 'px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white font-semibold rounded-lg transition text-sm',
  input: 'w-full px-4 py-3 bg-[#1a1d27] border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:border-blue-500 focus:outline-none transition',
  select: 'w-full px-4 py-3 bg-[#1a1d27] border border-gray-700 rounded-lg text-white focus:border-blue-500 focus:outline-none transition',
  textarea: 'w-full px-4 py-3 bg-[#1a1d27] border border-gray-700 rounded-lg text-white placeholder-gray-500 focus:border-blue-500 focus:outline-none resize-none transition',
  label: 'block text-sm font-semibold text-gray-300 mb-2',
  pageTitle: 'text-3xl font-bold text-white',
  sectionTitle: 'text-xl font-bold text-white',
  cardTitle: 'text-lg font-semibold text-white',
  bodyText: 'text-gray-300',
  mutedText: 'text-gray-400 text-sm',
  backBtn: 'flex items-center gap-2 text-blue-400 hover:text-blue-300 mb-6 transition font-semibold group',
  badgePending: 'px-3 py-1 bg-yellow-600/20 text-yellow-400 border border-yellow-600/30 rounded-full text-xs font-semibold',
  badgeApproved: 'px-3 py-1 bg-green-600/20 text-green-400 border border-green-600/30 rounded-full text-xs font-semibold',
  badgeRejected: 'px-3 py-1 bg-red-600/20 text-red-400 border border-red-600/30 rounded-full text-xs font-semibold',
  table: 'w-full border-collapse',
  tableHead: 'bg-[#252a37] text-gray-400 text-sm font-semibold uppercase tracking-wider',
  tableRow: 'border-b border-gray-700 hover:bg-[#252a37] transition',
  tableCell: 'px-6 py-4 text-gray-300',
  divider: 'border-t border-gray-700 my-6',
  emptyState: 'text-center py-12 text-gray-400',
};
